### ISSUE TITLE
phantomjs: command not found

### ISSUE THREAD

**Issue by PManager1** [yearofmoo-articles/AngularJS-SEO-Article#8]
I installed phantomjs using brew on my mac, and when i type phantomjs on my terminal it works. 

But, I get this error when i run below command on terminal. 

./make-snapshot.sh http://localhost:5757/#!/videos
./make-snapshot.sh: line 6: phantomjs: command not found

**Comment by jefffff** [comment]
i got the similar issue.

**Comment by PManager1** [comment]
The issue was , when i cloned this repo, it never downloaded the file .phantom-runner.js . 

It works now!
